---
title: "Winter R Bootcamp"
author: "Sean Kross"
date: "December 23, 2015"
output: html_document
---

## Welcome to the Winter R Bootcamp!

### Schedule

The Winter R Bootcamp will be taking place at the Johns Hopkins University
on January 6th, 8th, 11th, 13th, 20th, and 22nd from 1pm to 3:30pm.

### Contact

If you have any questions please send me an email: sean@seankross.com

### Homework and Grading

There will be no graded assignments or in-class assessments. To get the most out
of this course you should complete the [swirl](http://swirlstats.com)
courses that will be assigned at the end of each lecture. Students will recieve
no credit for this course.

### Syllabus

#### Lecture 1

- Installing R
    - [Notes](install.html)
    - [R Markdown](install.Rmd)
- The R Console & How to Read these Notes
    - [Notes](console.html)
    - [R Markdown](console.Rmd)
- Types & Logic
    - [Notes](types.html)
    - [R Markdown](types.Rmd)
- Data Structures
    - [Notes](datastr.html)
    - [R Markdown](datastr.Rmd)
- Flow Control
    - [Notes](flow.html)
    - [R Markdown](flow.Rmd)
- Loops
    - [Notes](loops.html)
    - [R Markdown](loops.Rmd)
- Functions
    - [Notes](functions.html)
    - [R Markdown](functions.Rmd)
- *Extras*
    - [swirl Exercises](hw1.html)
    - [Video Part 1](https://youtu.be/g-737UQlnBc)
    - [Video Part 2](https://youtu.be/Z6Z4ZXyKAOw)
    
#### Lecture 2

- Workspace & Files
    - [Notes](wf.html)
    - [R Markdown](wf.Rmd)
- Reading & Writing Data
    - [Notes](wr.html)
    - [R Markdown](wr.Rmd)
- *Extras*
    - [Data](https://raw.githubusercontent.com/seankross/lego/master/data-tidy/legosets.csv)
    - [Lego analysis](lego.html)
    - [Video Part 1](https://youtu.be/LvcUUaIrbVo)
    - [Video Part 2](https://youtu.be/iOafN_viXXo)
    
#### Lecture 3

- Plotting & Base Graphics
    - [Notes](plot.html)
    - [R Markdown](plot.Rmd)
- R Markdown
    - [Notes](rmd.html)
    - [R Markdown](rmd.Rmd)
- *Extras*
    - [swirl Exercises](hw2.html)
    - [Video Part 1](https://youtu.be/-qCfAuZUL54)
    - [Video Part 2](https://youtu.be/UjhOkpq2ta4)

#### Lecture 4

- Statistical Functions
    - [Notes](blank.html)
    - [R Markdown](blank.Rmd)
- Simulation
    - [Notes](blank.html)
    - [R Markdown](blank.Rmd)
- Test Functions
    - [Notes](blank.html)
    - [R Markdown](blank.Rmd)
- Basic Modeling
    - [Notes](blank.html)
    - [R Markdown](blank.Rmd)

#### Lecture 5

- Regex & `stringr`
    - [Notes](stringr.html)
    - [R Markdown](stringr.Rmd)
- `dplyr`
    - [Notes](dplyr.html)
    - [R Markdown](dplyr.Rmd)

    
#### Lecture 6

- Errors
    - [Notes](errors.html)
    - [R Markdown](errors.Rmd)
- Scope
    - [Notes](scope.html)
    - [R Markdown](scope.Rmd)
- `apply`
    - [Notes](apply.html)
    - [R Markdown](apply.Rmd)
- User Defined Operators
    - [Notes](operators.html)
    - [R Markdown](operators.Rmd)
- Pipes
    - [Notes](pipes.html)
    - [R Markdown](pipes.Rmd)


---

### License

All content contained within this site is licensed
[CC0](https://creativecommons.org/publicdomain/zero/1.0/), though if you do use
content from this site I'd love to hear about it.